### ISSUE TITLE
Missile System

### ISSUE THREAD

**Issue by MichalKrzyzanowski** [Richard-Fleming/Fort_MacArthur_Game#1]
## Description
The missile system let's the player fire a rocket by tapping anywhere on the screen, as long as it's above the level of the base.
Upon tapping, a rocket will be fired out from the missile system located in the base and travel in the direction of the tap. Once the rocket reaches the tapped location (rocket destination), the rocket should explode.

![image](https://user-images.githubusercontent.com/45101664/123068822-26c2e380-d40a-11eb-9ce0-a3fecc162f35.png)

## Tasks

- [x] **Task 1: Track Finger Position** 
- Find the player’s finger position and draw a line between it and the launcher’s position.
- If the player is still holding their finger to the screen, the line should update to follow. Taking the launcher as origin (0,0) If the missile’s projected vector’s Y value is ever less than the 0 (aiming under the launcher) and they release their finger, cancel the shot. (If the player’s finger position is under the launcher, cancel the shot.)

- [x] **Task 2: Have a Missile follow the Vector to the Finger Position** 
- On release of the player’s finger, launch a missile along the calculated vector towards the finger’s last position.
- The speed of the missile is variable via upgrades, with 3 units/second as a starting amount.

- [x] **Task 3: Have the Missile Explode** 
- Once the missile reaches its destination, delete the missile and replace it with a circle.
- The circle will start initially at 20 pixels and gradually increase to the max over the course of 2 seconds at a rate of 40 units per second, persisting at the max diameter of 100 pixels for an additional second before disappearing.

## Responsibilities
- Detect tap and store tap position
- Fire rockets
- Explode rockets

## Collaborators
- Particle System

## External Resources
[Direct Link to Feature in GDD](https://docs.google.com/document/d/13_bBHCj-OEVJtQcX1L58QInWUidVIlA6rL_KVhR33og/edit#heading=h.l3p0ylck1be7)
[Direct Link to Feature in TDD](https://docs.google.com/document/d/1zB88BcVOesHuKI2nW6Tc4w_azDc26Vv0ms2opMkryeA/edit#heading=h.a04dorma1f3e)
