### ISSUE TITLE
Enemy Planes

### ISSUE THREAD

**Issue by Joshua-Dunne** [Richard-Fleming/Fort_MacArthur_Game#10]
## Description
For our Game, we will need Enemy Planes for the Player to defend against. These Enemy Planes will cause the Player to take damage if they reach the base. Reaching the Base will reset the Plane for another attack.

## Tasks
- [x] Task 1: Render the Plane In Game
- Have the plane render in game.
- [x] Task 2: Have The Plane Follow a Random Vector
- Calculate the vector between the plane's random starting position and a random position at the bottom of the screen.
- The plane then follows this vector at a speed of 3 units/second.
- [x] Task 3: Have the Plane Return to the Top With a New Vector
- Once the plane passes the bottom of the screen, it’s given a new random starting position at the very top of the screen, the top left of the screen or the top right.
- The Plane is also given a new random destination at the bottom, prompting a new vector to follow.
- Whether or not the plane starts from the top right, left or very top is decided by another random number generator.
- [x] Task 4: The Plane Damages the Base
- If the plane manages to pass over the Base, the base takes damage, reducing health by 20%.

## Responsibilities
- Each Plane should give itself an initial starting point and direction to move towards.
- Each Plane should reset themselves when reaching the bottom of the screen.
- Each Plane should tell the Health System to lose HP when reaching the bottom of the screen.
- Each Plane should give itself a new starting point and direction to move towards when reaching the bottom of the screen.

## Collaborators
- Health System
- Missile System

## External Resources
[Direct Link to Feature in TDD](https://docs.google.com/document/d/1zB88BcVOesHuKI2nW6Tc4w_azDc26Vv0ms2opMkryeA/edit#heading=h.ht9a78lcm9s4)
[Direct Link to Feature in GDD](https://docs.google.com/document/d/13_bBHCj-OEVJtQcX1L58QInWUidVIlA6rL_KVhR33og/edit#heading=h.cssyq8cdi9en)
