### ISSUE TITLE
Sound Manager

### ISSUE THREAD

**Issue by MichalKrzyzanowski** [Richard-Fleming/Fort_MacArthur_Game#24]
## Description
The sound manager is responsible for loading and playing sound effects and music in the game.

## Tasks

- [x] **Task 1: Create the SoundManager class** 
- Create a class for the sound manager.
- Create a function for loading sound effects.
- Create functions for playing/stopping sound effects.

- [ ] **Task 2: Setup missile launch sound effect** 
- Load an appropriate sound effect.
- Play this sound effect when the missile is fired.

- [ ] **Task 3: Setup missile explosion sound effect** 
- Load an appropriate sound effect of an explosion.
- Play this sound effect as when the missile explodes.

- [ ] **Task 4: Setup plane movement sound effect** 
- Load an appropriate sound effect that loops well.
- Play this sound effect for every plane that is moving.

- [ ] **Task 5: Setup plane explosion sound effect** 
- Use the same explosion sound effect from the missile explosion.
- Play this sound effect for every plane explosion that occurred.

- [ ] **Task 6: Setup UI interaction sound effects** 
- Load two sound effects, one for tapping the buttons, another for backing out of certain screens (such as options).
-  Play the first sound effect when a button is tapped, play the second sound effect when a back button is pressed.

## Responsibilities
- Play sound effects
- Play background music

## Collaborators
- None

## External Resources
[Direct Link to Feature in GDD](https://docs.google.com/document/d/13_bBHCj-OEVJtQcX1L58QInWUidVIlA6rL_KVhR33og/edit#heading=h.i74bkhwilzue)
[Direct Link to Feature in TDD](https://docs.google.com/document/d/1zB88BcVOesHuKI2nW6Tc4w_azDc26Vv0ms2opMkryeA/edit#heading=h.51ctxlalsa4n)
