### ISSUE TITLE
Upgrade Manager

### ISSUE THREAD

**Issue by Joshua-Dunne** [Richard-Fleming/Fort_MacArthur_Game#27]
## Description
A separate system should be implemented to keep track of unlocked Upgrades for a level, and how much each Upgrade gives to the Player, so that Levels that are loaded in know of previous Upgrades the Player should have unlocked.

## Tasks

- [x] Task 1: Keep Track of Unlocked Upgrades per Level

When a Level is loaded, it should check and see what Upgrades are unlocked for that level. It will be done this way so that when the Player chooses a Level through the Level Selector, they will have any previous upgrades that would have been in-use automatically unlocked.

- [x] Task 2: Keep Track of amount Upgrades should apply

The Upgrade System should keep an internal track of how much each Upgrade should apply.
For example, if Upgrade 1 gives the Player more ammo, the Upgrade System will know how much more ammo the Player should get for that Level.
A final tally for each Upgrade will be kept. This means that if the Player has two ammo upgrades, the total amount of ammo that should be given to the Player will be told to the Level once it is loaded in.

- [ ] Task 3: Visually show Upgrades

If the Player has successfully unlocked an Upgrade, they should be able to see a visual representation of it on their screen, down near the base. This allows the Players see progression in real time.

## Responsibilities
- Keep Track of Upgrades that must be Unlocked for a Level.
- Keep Track of amount each Upgrade should apply.
- Keep Track of Upgrade final tallies that must be applied to each system.

## Collaborators
- Missile System
- Health System
- Ammo Management

## External Resources
[Direct Link to Feature in GDD](https://docs.google.com/document/d/13_bBHCj-OEVJtQcX1L58QInWUidVIlA6rL_KVhR33og/edit#heading=h.qvjbdt3bgwp0)
[Direct Link to Feature in TDD](https://docs.google.com/document/d/1zB88BcVOesHuKI2nW6Tc4w_azDc26Vv0ms2opMkryeA/edit#heading=h.yuz0srjgud5d)

**Comment by Joshua-Dunne** [comment]
Task 3 will be worked on later when we move onto visuals.
