### ISSUE TITLE
Health System

### ISSUE THREAD

**Issue by Joshua-Dunne** [Richard-Fleming/Fort_MacArthur_Game#4]
## Description
For our Game, we will need a Health Bar, so the Player can tell how much health they have left. This will also be used within our game logic to determine of the Player has run out of health, and reached a game over.

## Tasks
- [x] Task 1: Render the Bar
- Create the health bar design, and have it rendered in the game.
- [x] Task 2: Have the Bar Appearing and Disappearing
- The bars' opacity values can be tweaked to give it the appearing/disappearing quality. 
- When the player places their finger on the base, the health appears (opacity = 1) and upon releasing their finger from the base the health should disappear (opacity = 0). 
- These changes should be incremental by an amount of .1 a tick.
- [x] Task 3: Have the Bar Increase and Decrease
- Create two functions (one to increase the other to decrease health). 
- The increase can just be a full restore to full.
- The decreasing function should take a number variable as a parameter and subtract that value from the current health amount.

## Responsibilities
- Keeping track of HP value
- Giving Player visual clarity of their current health.
- Appearing when Player taps base, and disappearing shortly after to save screen room.

## Collaborators
- UI System

## External Resources
[Direct Link to Feature in TDD](https://docs.google.com/document/d/1zB88BcVOesHuKI2nW6Tc4w_azDc26Vv0ms2opMkryeA/edit#heading=h.8waewh7l5rcx)
[Direct Link to Feature in GDD](https://docs.google.com/document/d/13_bBHCj-OEVJtQcX1L58QInWUidVIlA6rL_KVhR33og/edit#heading=h.agoi67m8xhs5)

**Comment by MichalKrzyzanowski** [comment]
This should be our issue format going forward. Looks awesome!
