### ISSUE TITLE
Quiz Class

### ISSUE THREAD

**Issue by AllexisAlvarico** [Richard-Fleming/Fort_MacArthur_Game#8]
## Description
The quiz class is to allow the player to learn about the fort's history and equipment. The player will get buff if the player correctly done the quiz and if the player incorrectly answer the quiz they'll receive a debuff on their next level.

## Task
- [x] Task 1: Load In Quiz Questions And Screen
Store the questions/options and answers in a .Json file and ensure that the questions are formatted correctly when being portrayed in game.

- [x] Task 2: Accepting Responses To Questions
Allow the user to select an option from a list of answers. The correct answer will be stored in the above .Json file.

- [x] Task 3: Check if answered correctly
Cross reference the selected option with the correct option in our .Json file. Give feedback to the player about whether they answered correctly or not. (I used a green highlight on the button for correct and red for wrong previously)

- [x] Task 4: Show blurb for building off the answer
Once the answer has been logged and processed display a blurb of information that doesn’t give away the answer but hints at it.

- [x] Task 5: When answered send bool back to main thread
We need to know if the user got the answer correct or not. We will need a variable that can be passed from the quiz thread to the main thread for validating these conditions.

## Collaborators
- Player
- UI
- Missile battery
- Level Manager
- Ammo manager
## Responsibilities
- Gives the player the quiz after the level is finished.
- Gives out bonuses if the quiz is correctly answered.
- Gives out punishment if the quiz is incorrectly answered.

## More Detail
 - [TDD: Quiz](https://docs.google.com/document/d/1zB88BcVOesHuKI2nW6Tc4w_azDc26Vv0ms2opMkryeA/edit#heading=h.79y4pr83p128)
